src/objects/Agent__c.object
<CustomObject>
    <description>it is the object which will contain all the companies that will accept new candidate from (i.e. new referrer is coming from)</description>
    <fields>
        <fullName>url__c</fullName>
        <description>the Agent URL</description>
        <label>url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Agent</label>
    <nameField>
        <label>Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <fields>
        <fullName>LinkedIn_Profile_URL__c</fullName>
        <description>it should contains the candidates LinkedIn Profile URL</description>
        <label>LinkedIn_Profile_URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Referrer_Email__c</fullName>
        <description>This field contains the email who referred candidate to Box</description>
        <label>Referrer_Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <defaultValue>&quot;Individual&quot;</defaultValue>
        <description>contains the agency name which have uploaded the resume otherwise it will be individual</description>
        <label>Source</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Business Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product and Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Operations</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ReferralController.cls
public with sharing class ReferralController {

    public Document resume{
        get{
            if(resume == null){
                resume = new Document();
            }
            return resume;
        }
        set;
    }
    
    public Agent__c agent{
        public get;
        public set;
    }
    
    public Candidate__c candidate{
        public get;
        public set;
    }
    
    public ReferralController(){
        candidate = new Candidate__c();
        agent = new Agent__c(); 
        position = new Position__c();   
    }
    
    private boolean validation(){
        try{
            ApexPages.Message errorMessage;
            
            if(resume != null && resume.name != null && !(resume.name.contains('.doc') || resume.name.contains('.docx') || resume.name.contains('.pdf'))){
                errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'invalid file type');
                ApexPages.addMessage(errorMessage); 
                return null;
            }

           if(candidate.Referrer_Email__c != null && !candidate.Referrer_Email__c.contains('box.com')){
               errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'invalid email address for box employee, please use your @box.com email');
               ApexPages.addMessage(errorMessage); 
               return null;
           }
              
           if(resume == null && (candidate.LinkedIn_Profile_URL__c == null || candidate.LinkedIn_Profile_URL__c.length() < 1)){
               errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'you need either Resume document or LinkedIn Profile');
               ApexPages.addMessage(errorMessage); 
               return null;
           }
           
           if(candidate.LinkedIn_Profile_URL__c != null && candidate.LinkedIn_Profile_URL__c.length() > 0 && candidate.LinkedIn_Profile_URL__c.contains('LinkedIn.com') == false){
               errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'valid LinkedIn Profile URL');
               ApexPages.addMessage(errorMessage); 
               return null;
           }

           if(candidate.Street__c == null || candidate.Street__c.length() < 1){
               //since this is required in the candidate object but the employee may/maynot know it therefore I am setting default value if it has no value
               candidate.Street__c = 'Anywhere';
           }

        }catch(Exception e){
            ApexPages.Message catchErrorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
            ApexPages.addMessage(catchErrorMessage); 
            return null;
        }
        return true;
    }
    
    //for debug only
    public String responseBody{get; private set;}
    
    public ParsedResume parsedResume{get; private set;}
    
    public PageReference employeeReferreralAction(){
        if(validation() != null){
            try{
                if(resume != null && resume.name != null){
                    BoxUpload boxUpload = new BoxUpload(resume);
                    responseBody = boxUpload.getUploadedFileId();
                }
                candidate.Source__c = 'Employee Referreral';
                insert candidate;
            }catch(Exception e){
                ApexPages.Message catchErrorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
                ApexPages.addMessage(catchErrorMessage); 
                return null;
            }
            return new PageReference('/apex/ApplyComplete');
        }
        return null;
    }
    
    public PageReference agentReferralAction(){
        if(validation() != null){
            try{
                if(resume != null && resume.name != null){
                    BoxUpload boxUpload = new BoxUpload(resume);
                    responseBody = boxUpload.getUploadedFileId();
                }
                candidate.Source__c = 'Agent ' + Agent.Name;
                insert candidate;
            }catch(Exception e){
                ApexPages.Message catchErrorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
                ApexPages.addMessage(catchErrorMessage); 
                return null;
            }
            return new PageReference('/apex/ApplyComplete');
        }
        return null;
    }
    
    //delete me after test
    public String message{
        public get;
        public set;
    }
    
    public PageReference verifyAgentAction(){
        try{
            Agent__c selectedAgent = [select Name, url__c from Agent__c where url__c = :agent.url__c and Name =:Agent.Name];
            if(selectedAgent != null){
                return new PageReference('/apex/AgentReferral'); 
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'it is not listed there')); 
            }
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid Agent credentials')); 
        }
        return null;
    }
    
    public List<selectOption> departmentsList {
    public get {
        List<selectOption> departmentsList = new List<selectOption>();
            for (position__c department : [select department__c from position__c]){
                departmentsList.add(new selectOption(department.department__c, department.department__c));
            }
            return departmentsList;
        }
        private set;
    }
    
    public List<selectOption> positionsList{
        public get{
            List<selectOption> positionsList = new List<selectOption>();
            for (Position__c positionItem : [select Name from Position__c]){
                positionsList.add(new selectOption(positionItem.Name, positionItem.Name));
            }
            positionsList.add(new selectOption('null', 'null'));
            return positionsList;
        }
        
        public set;
    }
    
    public List<selectOption> testPositionsList{
        public get{
            List<selectOption> positionsList = new List<selectOption>();
            for (Position__c positionItem : [select Name from Position__c where Department__c = 'Engineering']){
                positionsList.add(new selectOption(positionItem.Name, positionItem.Name));
            }
            return positionsList;
        }
        
        public set;
    }
    
    public String getPositionListDynamically(String departmentName){
        return 'From Dynamic Method: ' + departmentName;
    }
    
    public Position__c position{
        public get;
        public set;
    }
    
     /*------------ Tests only below this line ------------*/
    static testMethod void testApplyAgentController(){
        ReferralController ttt = new ReferralController();
        ttt.validation();
        ttt.employeeReferreralAction();
    
    }
}