src/objects/Application__c.object
<CustomObject>
    <description>An application for a position offered at Box.</description>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer in process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ApplicationChartsExtension.cls
global with sharing class ApplicationChartsExtension {
    public final Application__c application;
    public ApplicationChartsExtension(ApexPages.StandardController ApplicationController) {
        this.application=(Application__c)ApplicationController.getRecord();
    }
    
    @RemoteAction  
    global static AggregateResult[] loadApplicationStatus() {
        return [select count(Id) CandidateNum, Status__c, Position__c from Application__c group by Position__c, Status__c];
    }  
    
   
}