src/objects/Application__c.object
<CustomObject>
    <description>An application for a position offered at Box.</description>
    <fields>
        <fullName>Box_Resume_Id__c</fullName>
        <description>Resume id of a resume stored in Box. Used to retreive a resume and display embedded in a page.</description>
        <label>Box_Resume_Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Candidate who is applying.</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resume_Text__c</fullName>
        <description>Textual version of a resume.</description>
        <label>Resume Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ApplyController.cls
public with sharing class ApplyController {    
    
    public Document resume{
        get{
            if(resume == null){
                resume = new Document();
            }
            return resume;
        }
        set;
    }
        
    //for debug only
    public String responseBody{get; private set;}
    
    public ParsedResume parsedResume{get; private set;}    
    
    //Go from Page 1 (upload) to Page 2 (resume text)
    public pageReference uploadAction(){
        parsedResume = new ParsedResume(resume);
        return new PageReference('/apex/ApplyResumeText');
    }
    
    //Go from Page 2 (resume text) to Page 3 (fill fields, submit app)
    public pageReference resumeTextAction(){
        parsedResume.parseToXML();
        return new PageReference('/apex/ApplySubmit');
    }
    
    //Go from Page 3 (fill & submit) to Page 4 (confirmation)
    public pageReference submitAction(){
        //upload Resume to Box
        BoxUpload boxUpload = new BoxUpload(resume);
        responseBody = boxUpload.getUploadedFileId();
    
	    //create Candidate       
    	insert parsedResume.c;
    
        //create Application
        Application__c a = new Application__c();
        a.Box_Resume_Id__c = boxUpload.getUploadedFileId();
        a.Candidate__c = parsedResume.c.Id;
        a.Resume_Text__c = parsedResume.resumeText;
        a.Position__c = [SELECT Id FROM Position__c].get(0).Id;
        insert a;
        return new PageReference('/apex/ApplyComplete');
    }
}