src/objects/Application__c.object
<CustomObject>
    <description>An application for a position offered at Box.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Candidate who is applying.</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer in process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <fields>
        <fullName>Code_Red__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Candidates that need to be expedited through the hiring process are marked as &quot;code red&quot; candidate.</description>
        <label>Code_Red</label>
        <type>Checkbox</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DashboardRedZoneController.cls
public class DashboardRedZoneController{

public Integer getOfferInProgressNum() {
    return [select count() from Application__c where Status__c='Offer in process' and CreatedDate<=NEXT_WEEK];
}

public Integer getCodeRedNum() {
    return [select count() from Candidate__c where Code_Red__c=true and CreatedDate<=NEXT_WEEK];
}


 /*------------ Tests only below this line ------------*/
    static testMethod void testDashboardRedZoneController(){
    DashboardRedZoneController t = new DashboardRedZoneController();
      t.getOfferInProgressNum();
      t.getCodeRedNum();      
    }

 
}