src/objects/Application__c.object
<CustomObject>
    <description>An application for a position offered at Box.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer in process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SummarySidebarController.cls
public class SummarySidebarController{
 
public Integer getNewApplication() {
return [
select count() from Application__c
where Status__c='New'
];
}
 
public Integer getPhoneScreen() {
return [
select count() from Application__c
where Status__c='Recruiter Screen'
OR Status__c='HM Screen'
];
}
 
public Integer getOnsite() {
return [
select count() from Application__c
where Status__c='Onsite Interview'
];
}



 
static testMethod void testSummarySidebarController() {
Test.setCurrentPageReference(new PageReference('Page.SidebarSummary'));
SummarySidebarController controller = new SummarySidebarController();
Integer i1 = controller.getNewApplication();
Integer i2 = controller.getPhoneScreen();
Integer i3 = controller.getOnsite();

}
 
}