src/objects/Application__c.object
<CustomObject>
    <description>An application for a position offered at Box.</description>
    <fields>
        <fullName>Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer in process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Email_Reminder__c.object
<CustomObject>
    <fields>
        <fullName>ApplicationID__c</fullName>
        <externalId>true</externalId>
        <label>ApplicationID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Email Reminders</relationshipLabel>
        <relationshipName>Email_Reminders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Email_Datetime__c</fullName>
        <label>Last Email Datetime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Email Reminder</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>EmailReminderId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Reminders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Scheduled_email_notice.cls
global class Scheduled_email_notice implements Schedulable {
    
     global void execute(SchedulableContext SC){
                  
        Datetime now = System.now();
        Datetime now3 = now.addDays(-3);

        // Let's get out the list of applications that are over the 3 days mark
        List<Application__c> applications = [SELECT Id,Name,Coordinator__r.Email FROM Application__c WHERE (Status__c != 'Rejected' OR Status__c != 'Accepted' OR Status__c != 'Submitted Rejection' OR Status__c != 'Recruiter Screen Rejection' OR Status__c != 'HM Screen Rejection') AND LastModifiedDate <=: now3 AND Id NOT IN (SELECT Application__c FROM Email_Reminder__c WHERE Last_Email_Datetime__c >: now3)];

        //set up email parametres
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSenderDisplayName('Box.com');
        mail.setSenderDisplayName('Box Recruiting System');
        mail.setReplyTo('msit-practicum-box@googlegroups.com');
        mail.setSubject('Notice');

        //using template
        //EmailTemplate et = [SELECT id FROM EmailTemplate WHERE Name = 'reject_template'];
        //mail.setTemplateId(et.id);

        //iterate List for email and upsert 
        String email=null;
        for(Application__c application:applications){

            // Upsert to Email_Reminder__c
            Email_Reminder__c newRecord= new Email_Reminder__c(Application__c=application.Id, ApplicationID__c=application.Name, Last_Email_Datetime__c=now);
            try {
                upsert newRecord ApplicationID__c;
            } catch (DmlException e) {
                System.debug(e.getMessage());
            }

            // set up email specific parametres
            mail.setPlainTextBody(
                'Application: '+application.Name+' '+' has idled in system for 3 days without any updates. '   + '.\n' 
            );
            mail.setToAddresses(new String[] {application.Coordinator__r.Email});  
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});//sent 
        }
    }
}