src/objects/Application__c.object
<CustomObject>
    <description>An application for a position offered at Box.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Candidate who is applying.</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/EmailCommunication__c.object
<CustomObject>
    <description>it is the object used to store email communication between the candidates and the HR or hiring manager</description>
    <fields>
        <fullName>CandidateSender__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this value will be true if the Candidate is the sender i.e. if this email was received by the platform from a candidate</description>
        <label>CandidateSender</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <description>it will determines the candidate who is communicated</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>EmailCommunications</relationshipLabel>
        <relationshipName>EmailCommunications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>it will contains the message which the Box employee has sent or received from the candidate</description>
        <inlineHelpText>it will contains the message which the Box employee has sent or received from the candidate</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>is the subject line for the message</description>
        <label>Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>EmailCommunication</label>
    <nameField>
        <label>Emails Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EmailCommunications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmbeddedEmailController.cls
public class EmbeddedEmailController{

     public List<EmailCommunication__c> emailCommunication{
         public get;
         public set;
     }
     
     public boolean test{
         public get;
         public set;
     }
     
     /**
     * @description this is the class contructor for the standard controller. this will allow for visualforce page
     * to show the communication between the HR and a candidate
     * @param StdController it will pass the Candidate Id to the contructor to get the right candidate
     */
     public EmbeddedEmailController(ApexPages.StandardController stdController) {
        Id candidateId = stdController.getId();
        emailCommunication = [SELECT Candidate__c, CandidateSender__c, Message__c, Subject__c FROM EmailCommunication__c WHERE Candidate__c = :candidateId];

    }
    
    /*------------ Tests only below this line ------------*/
    static testMethod void testEmbeddedEmailController(){
        Application__c a = new Application__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        EmbeddedEmailController eec = new EmbeddedEmailController(sc);
    }
}