src/objects/Application__c.object
<CustomObject>
    <description>An application for a position offered at Box.</description>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Hires by Source</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Job Board</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Referral</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sourced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer in process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Hires__c</fullName>
        <description>Indicate the goal that how many people need to be hired for this positon.</description>
        <inlineHelpText>Indicate the goal that how many people need to be hired for this positon.</inlineHelpText>
        <label>Number of Hires</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ChartsExtension.cls
global with sharing class ChartsExtension {
    public final Application__c application;
    public ChartsExtension (ApexPages.StandardController ApplicationController) {
        this.application=(Application__c)ApplicationController.getRecord();
    }
    
    @RemoteAction  
    global static AggregateResult[] loadNewStatus() {        
        return [select Position__r.Name position, count(Status__c) newNum from Application__c where Status__c= 'new' group by Position__r.Name];
    }  
    
    @RemoteAction  
    global static AggregateResult[] loadPhoneScreenStatus() {        
        return [select Position__r.Name position, count(Status__c) phoneNum from Application__c where Status__c= 'Recruiter Screen' or Status__c='HM Screen' group by Position__r.Name];
    } 
    
    @RemoteAction  
    global static AggregateResult[] loadOnsiteStatus() {        
        return [select Position__r.Name position, count(Status__c) onsiteNum from Application__c where Status__c= 'Onsite Interview' group by Position__r.Name];
    }   
    
    @RemoteAction  
    global static AggregateResult[] loadOfferInProgressStatus() {        
        return [select Position__r.Name position, count(Status__c) offerInProgressNum from Application__c where Status__c= 'Offer in process' group by Position__r.Name];
    } 
    
    @RemoteAction  
    global static AggregateResult[] loadOfferAcceptedStatus() {        
        return [select Position__r.Name position, count(Status__c) offerAcceptedNum from Application__c where Status__c= 'Accepted' group by Position__r.Name];
    } 
    
    @RemoteAction  
    global static AggregateResult[] loadGoalActualGauge() {        
        return [select count(Id) actual from Application__c where Status__c='Accepted'];                
    } 
    
    @RemoteAction  
    global static AggregateResult[] loadGoalTargetGauge() {        
        return [select sum(Number_of_Hires__c) target from Position__c];                
    } 
    
    @RemoteAction  
    global static Set<String> loadPositions() {        
        LIST<Application__c> positions = [select Position__r.Name from Application__c]; 
        Set<String> positionset = new Set<String>();               
        for (Integer i = 0; i< positions.size(); i++){
            positionset.add(positions[i].Position__r.Name); // contains distinct position
        }
        return positionset;
    } 
    
    @RemoteAction  
    global static AggregateResult[] loadCandidateSources(string position) {        
        return [select count(Id) SourceNum, Source__c, Position__r.Name pos from Application__c where Position__r.Name=:position group by Source__c, Position__r.Name];                
    }
    
     /*------------ Tests only below this line ------------*/
    static testMethod void testChartsExtension(){
        Application__c a = new Application__c();
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        ChartsExtension ce = new ChartsExtension(sc);
        loadNewStatus();
        loadPhoneScreenStatus();
        loadOnsiteStatus();
        loadOfferInProgressStatus();
        loadOfferAcceptedStatus();
        loadGoalActualGauge();
        loadGoalTargetGauge();
    }
   
}