src/objects/Application__c.object
<CustomObject>
    <description>An application for a position offered at Box.</description>
    <fields>
        <fullName>Candidate_Formula__c</fullName>
        <formula>Candidate__r.First_Name__c
&amp;
&quot; &quot;
&amp;
Candidate__r.Last_Name__c</formula>
        <label>Candidate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Candidate who is applying.</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruiter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recruiter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Hires by Source</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Job Board</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Referral</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sourced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiter Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen Rejection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offer in process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>ApplicationID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <fields>
        <fullName>Code_Red__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Candidates that need to be expedited through the hiring process are marked as &quot;code red&quot; candidate.</description>
        <label>Code_Red</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the candidate.</description>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the candidate.</description>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <defaultValue>&quot;Individual&quot;</defaultValue>
        <description>contains the agency name which have uploaded the resume otherwise it will be individual</description>
        <label>Source</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Commentor__c.object
<CustomObject>
    <description>Box employee who leaves comments for a candidate.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If user is a department head or hiring manager, this field should be linked to its customer portal account</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commentors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commentor</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>CommentorID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flagged_Junction__c.object
<CustomObject>
    <description>Junction object to support the many-to-many relationship between a Candidate and a Commentor (User) for Flagging a candidate. Flagged candidates work like starred messages in Gmail.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <description>Flagged candidate.</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Flagged Junctions</relationshipLabel>
        <relationshipName>Flagged_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commentor__c</fullName>
        <description>User who has flagged a candidate.</description>
        <label>Commentor</label>
        <referenceTo>Commentor__c</referenceTo>
        <relationshipLabel>Flagged Junctions</relationshipLabel>
        <relationshipName>Flagged_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Flagged Junction</label>
    <nameField>
        <label>Flagged Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flagged Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interview__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application for which this interview was performed.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Candidate_Formula__c</fullName>
        <formula>HYPERLINK
( Application__r.Candidate__r.Id ,
Application__r.Candidate__r.First_Name__c
&amp;
&quot; &quot;
&amp;
Application__r.Candidate__r.Last_Name__c )</formula>
        <label>Candidate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interview_Type__c</fullName>
        <label>Interview Type</label>
        <picklist>
            <picklistValues>
                <fullName>Recruiter Screen</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>HM Screen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite Interview</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Interview</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>InterviewID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Business Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product and Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Operations</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <description>The open date to hire for the postion</description>
        <inlineHelpText>The open date to hire for the postion</inlineHelpText>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Review__c.object
<CustomObject>
    <description>Comments and a rating of a candidate, often after a phone screen or interview.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application for which this review was performed.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Review</relationshipLabel>
        <relationshipName>Review</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <formula>HYPERLINK(
Application__r.Candidate__r.Id,
Application__r.Candidate__r.First_Name__c
&amp;
&quot; &quot;
&amp;
Application__r.Candidate__r.Last_Name__c)</formula>
        <label>Candidate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commentor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>User of authenticated sites.</description>
        <label>Commentor</label>
        <referenceTo>Commentor__c</referenceTo>
        <relationshipLabel>Review</relationshipLabel>
        <relationshipName>Review</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interview_Datetime__c</fullName>
        <label>Interview Date/Time (PST)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interview__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Interview</label>
        <referenceTo>Interview__c</referenceTo>
        <relationshipLabel>Review</relationshipLabel>
        <relationshipName>Review</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <formula>Application__r.Position__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>ReviewID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DashboardController.cls
public class DashboardController{

public Integer getOfferInProgressNum() {
    return [SELECT count() FROM Application__c WHERE Status__c='Offer in process' AND CreatedDate<=NEXT_WEEK  AND (Recruiter__c = :UserInfo.getUserId() OR Hiring_Manager__c = :UserInfo.getUserId() OR Coordinator__c = :UserInfo.getUserId())];
}

public Integer getCodeRedNum() {
    return [SELECT count() FROM Candidate__c WHERE Code_Red__c=true AND CreatedDate<=NEXT_WEEK];
}

public LIST<Review__c> getTodayPhoneScreens () {
    LIST<Review__c> TodayPhoneScreens = new LIST<Review__c>();
    LIST<Review__c> reviews = [SELECT Application__c FROM Review__c WHERE (Interview__r.Interview_Type__c='Recruiter Screen' OR Interview__r.Interview_Type__c='HM Screen') AND Interview_Datetime__c = TODAY AND (Application__r.Recruiter__c = :UserInfo.getUserId() OR Application__r.Hiring_Manager__c = :UserInfo.getUserId() OR Application__r.Coordinator__c = :UserInfo.getUserId())]; 
    Set<String> reviewID = new Set<String>();
    for(Integer i = 0; i < reviews.size(); i++){
         reviewID.add(reviews[i].Application__c);           
    }
    Review__c review = new Review__c(); 
    Iterator<String> iterator = reviewID.iterator();
    while(iterator.hasNext()) {
         String applicationID = iterator.next();
         review = [SELECT Id, Application__c, Application__r.Name, Candidate_Formula__c, Position__c, Interview__r.Interview_Type__c FROM Review__c
                  WHERE Application__c = :applicationID].get(0);               
         TodayPhoneScreens.add(review); // contains distinct interviews
    } 
            
    return TodayPhoneScreens;         
}


public LIST<Review__c> getTodayOnsites () {
    LIST<Review__c> TodayOnsites = new LIST<Review__c>();
    LIST<Review__c> reviews = [SELECT Application__c FROM Review__c WHERE Interview__r.Interview_Type__c='Onsite Interview' AND Interview_Datetime__c = TODAY AND (Application__r.Recruiter__c = :UserInfo.getUserId() OR Application__r.Hiring_Manager__c = :UserInfo.getUserId() OR Application__r.Coordinator__c = :UserInfo.getUserId())]; 
    Set<String> reviewID = new Set<String>();
    for(Integer i = 0; i < reviews.size(); i++){
         reviewID.add(reviews[i].Application__c);           
    }
    Review__c review = new Review__c(); 
    Iterator<String> iterator = reviewID.iterator();
    while(iterator.hasNext()) {
         String applicationID = iterator.next();
         review = [SELECT Id, Application__c, Application__r.Name, Candidate_Formula__c, Position__c, Interview__r.Interview_Type__c FROM Review__c
                  WHERE Application__c = :applicationID].get(0);               
         TodayOnsites.add(review); // contains distinct interviews
    }
    
  
            
    return TodayOnsites;         
}

public LIST<Flagged_Junction__c> getFlaggedCandidates() {
    LIST<Flagged_Junction__c> Candidates = [SELECT Candidate__c FROM Flagged_Junction__c
                                            WHERE Commentor__r.User__c =: UserInfo.getUserId()];
    LIST<Application__c> applications = new LIST<Application__c>();
    for(Integer i = 0; i < Candidates.size(); i++){
        applications = [SELECT Position__c, Status__c FROM Application__c 
                        WHERE Candidate__c = :Candidates[i].Candidate__c];
    }
       
    LIST<Flagged_Junction__c> FlaggedCandidates = [SELECT Id, Name, Candidate__c, Candidate__r.First_Name__c, Candidate__r.Last_Name__c FROM Flagged_Junction__c
                                                   WHERE Commentor__r.User__c =: UserInfo.getUserId()];                 
       
    return FlaggedCandidates;   
                                   
}

public LIST<Application__c> getPendingCandidates(){
    LIST<Application__c> PendingCandidates = [SELECT Id, Name, Candidate_Formula__c, Position__c, Status__c  FROM Application__c
                                              WHERE (Status__c = 'New' OR Status__c = 'Recruiter Screen' OR Status__c = 'HM Screen' OR Status__c = 'Onsite Interview' OR Status__c = 'Offer in process') AND (Recruiter__c = :UserInfo.getUserId() OR Hiring_Manager__c = :UserInfo.getUserId() OR Coordinator__c = :UserInfo.getUserId())];
    
    return PendingCandidates;

}

public LIST<Application__c> getTeamQuarterlyHiredList(){
    LIST<Application__c> TeamQuarterlyHiredList = [SELECT Id, Candidate__r.First_Name__c, Candidate__r.Last_Name__c, Position__c, Position__r.Department__c, Source__c FROM Application__c WHERE Status__c = 'Accepted' AND Position__r.Open_Date__c = THIS_QUARTER];
    return TeamQuarterlyHiredList;
}

    
  

 /*------------ Tests only below this line ------------*/
    static testMethod void testDashboardController(){
    DashboardController dc = new DashboardController();
      dc.getOfferInProgressNum();
      dc.getCodeRedNum();
      dc.getTodayPhoneScreens();
      dc.getTodayOnsites();
      dc.getFlaggedCandidates();
      dc.getPendingCandidates();
      dc.getTeamQuarterlyHiredList();      
    }

 
}