src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Commentor__c.object
<CustomObject>
    <description>Box employee who leaves comments for a candidate.</description>
    <label>Commentor</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>CommentorID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commentors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flagged_Junction__c.object
<CustomObject>
    <description>Junction object to support the many-to-many relationship between a Candidate and a Commentor (User) for Flagging a candidate. Flagged candidates work like starred messages in Gmail.</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <description>Flagged candidate.</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Flagged Junctions</relationshipLabel>
        <relationshipName>Flagged_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commentor__c</fullName>
        <description>User who has flagged a candidate.</description>
        <label>Commentor</label>
        <referenceTo>Commentor__c</referenceTo>
        <relationshipLabel>Flagged Junctions</relationshipLabel>
        <relationshipName>Flagged_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Flagged Junction</label>
    <nameField>
        <label>Flagged Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flagged Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FlagCandidateController.cls
global class FlagCandidateController{

    //public Candidate__c candidate;
    //public Commentor__c commentor;   

    WebService static void Flag(string candidateID, string commentorID){
        //Candidate__c candidate = [select Id from Candidate__c where Id=:candidateID].get(0);
        //Commentor__c commentor = [select Id from Commentor__c where Id=:commentorID].get(0);
        
        
        Flagged_Junction__c newFlag = new Flagged_Junction__c(Candidate__c=candidateID, Commentor__c=commentorID);
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.useDefaultRule = true;
        newFlag.setOptions(dmlOpts);
                    
        // Insert the new position
        INSERT newFlag;
        return;                          
     }
        
     public PageReference Unflag() {
         return null;
     }
}