src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address of the candidate.</description>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the candidate.</description>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the candidate.</description>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/EmailCommunication__c.object
<CustomObject>
    <description>it is the object used to store email communication between the candidates and the HR or hiring manager</description>
    <fields>
        <fullName>CandidateSender__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this value will be true if the Candidate is the sender i.e. if this email was received by the platform from a candidate</description>
        <label>CandidateSender</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <description>it will determines the candidate who is communicated</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>EmailCommunications</relationshipLabel>
        <relationshipName>EmailCommunications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>it will contains the message which the Box employee has sent or received from the candidate</description>
        <inlineHelpText>it will contains the message which the Box employee has sent or received from the candidate</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>is the subject line for the message</description>
        <label>Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>EmailCommunication</label>
    <nameField>
        <label>Emails Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EmailCommunications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmailProcessor.cls
global class EmailProcessor implements Messaging.InboundEmailHandler {
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        EmailCommunication__c emailCommunication = new EmailCommunication__c();
        emailCommunication.CandidateSender__c = true;
        emailCommunication.Message__c = email.plainTextBody;
        emailCommunication.Subject__c = email.Subject;
        emailCommunication.Candidate__c = [select id from Candidate__c where email__c = :email.fromAddress limit 1].id;
        insert emailCommunication;
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        return result;
    }
      
    /*------------ Tests only below this line ------------*/
    static testMethod void testEmailProcessor(){
        //create email
        Messaging.InboundEmail email = new Messaging.InboundEmail();        
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        Candidate__c c = new Candidate__c();
        c.email__c = 'user@user.com';
        c.first_name__c = 'first';
        c.last_name__c = 'last';
        insert c;
        email.fromAddress = c.email__c;

        //run test
        EmailProcessor ep = new EmailProcessor();
        ep.handleInboundEmail(email, envelope);
    }
  }