src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Employer__c</fullName>
        <label>Current Employer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Title__c</fullName>
        <label>Current Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address of the candidate.</description>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the candidate.</description>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the candidate.</description>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>University__c</fullName>
        <description>Most recent university that the applicant has studied at.</description>
        <label>University</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ParsedResume.cls
public with sharing class ParsedResume {

    /*resumeText: is string which contains the text of the resume
    */
    public String resumeText{get; set;}
    
    /*resumeXML: is string which contains the parsed resume of the text.
      it differs from the resume text that contains the resume as parsed xml version
      rather than plain resume text
    */
    private String resumeXML;
    
    /** Candidate: is customized Object that corresponds to Job Applicant
    */
    public Candidate__c c{get; set;}
    
    /**
        sovren: which contains all sovren methods to parse and convert resumes
    */
    private sovrenCom.ConvertAndParseSoap sovren;

    /* Given a resume Document, uses Sovren to parse the document, and
     * stores the raw text in resumeText, and stores the HR-XML in resumeXML
     
         resumeDoc: is object which will contains the resume binaries and 
         pass it to sovren webservice
     */
    public ParsedResume(Document resumeDoc) {
        sovren = new sovrenCom.ConvertAndParseSoap();        
        if (resumeDoc != null) {
            resumeText = sovren.DoConversionSimplified(EncodingUtil.Base64Encode(resumeDoc.body),'PLAIN_TEXT');            
        }
    }
    
    /* Sends the resume text to Sovren to be parsed. Stores the HR-XML result in resumeXML. 
     */
    public void parseToXML() {
        resumeXML = sovren.ParseConvertedResume(resumeText , false, false, 5000, 2,'1', false,'1');
        c = new Candidate__c();

        c.First_Name__c = getFirstField('GivenName');
        c.Last_Name__c = getFirstField('FamilyName');
        c.Phone__c = getFirstField('FormattedNumber');
        c.Email__c = getFirstField('InternetEmailAddress');
        
        c.Street__c = getFirstField('AddressLine');
        c.City__c = getFirstField('Municipality');
        c.State__c = getFirstField('Region');
        c.Zip_Code__c = getFirstField('PostalCode');
        
        c.University__c = getFirstField('SchoolName');
        
        c.Current_Employer__c = getFirstField('EmployerOrgName');
        c.Current_Title__c = getFirstField('Title');        
    }
    
    /* Helper method to populate variables
     * Returns the contents of the first XML element identified by fieldName 
     */
    private String getFirstField(String fieldName) {
        XMLDom xmlDom = new XMLDom(resumeXML);
        try {
            return xmlDom.getElementsByTagName(fieldName).get(0).nodeValue;
        } catch (System.ListException e) {
            return '';
        }
    }
}