src/objects/Candidate__c.object
<CustomObject>
    <description>A candidate applying to a position at Box.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address of the candidate.</description>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the candidate.</description>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the candidate.</description>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>CandidateID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/EmailCommunication__c.object
<CustomObject>
    <description>it is the object used to store email communication between the candidates and the HR or hiring manager</description>
    <fields>
        <fullName>CandidateSender__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this value will be true if the Candidate is the sender i.e. if this email was received by the platform from a candidate</description>
        <label>CandidateSender</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <description>it will determines the candidate who is communicated</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>EmailCommunications</relationshipLabel>
        <relationshipName>EmailCommunications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>it will contains the message which the Box employee has sent or received from the candidate</description>
        <inlineHelpText>it will contains the message which the Box employee has sent or received from the candidate</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>is the subject line for the message</description>
        <label>Subject</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>EmailCommunication</label>
    <nameField>
        <label>Emails Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EmailCommunications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmailSender.cls
public class EmailSender{

    
    public List<Candidate__c> candidateList{
        public get;
        public set;
    }
    
    public String candidateEmail{
        public get;
        public set;
    }
    
    public EmailCommunication__c emailCommunication{
        public get;
        public set;
    }
    
    public boolean html{
        get;
        set;
    }
    
    public EmailSender(){
       emailCommunication = new emailCommunication__c();
       candidateList = [select First_Name__c, Last_Name__c, Email__c from Candidate__c];
    }
    
    public List<SelectOption> getCandidates() {
        List<SelectOption> options = new List<SelectOption>();
        for(Integer i = 0; i < candidateList.size(); i++){ 
            options.add(new SelectOption(candidateList.get(i).Email__c, candidateList.get(i).First_Name__c + ' ' + candidateList.get(i).Last_Name__c));
        }
        return options;
    }

    public PageReference sendEmail(){
        try{
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            Candidate__c selectedCandidate = [select id, First_Name__c, Last_Name__c, Email__c from Candidate__c where Email__c = :candidateEmail limit 1];  
            String[] toAddresses = new String[] {selectedCandidate.Email__c}; 
            mail.setToAddresses(toAddresses);
            EmailServicesAddress emailServicesAddress = [select LocalPart, EmailDomainName from EmailServicesAddress limit 1];
            mail.setReplyTo(emailServicesAddress.LocalPart + '@' + emailServicesAddress.EmailDomainName);       
            mail.setSenderDisplayName(UserInfo.getOrganizationName());   
            mail.setSubject(emailCommunication.Subject__c);  
            mail.setBccSender(false);
            mail.setUseSignature(false);   
            mail.setPlainTextBody(emailCommunication.Message__c);
            //mail.setHtmlBody('Your case:<b> ' + case.Id +' </b>has been created.<p>'+
                 //'To view your case <a href=https://na1.salesforce.com/'+case.Id+'>click here.</a>');     
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            emailCommunication.CandidateSender__c = false;
            emailCommunication.Candidate__c = selectedCandidate.id;
            insert emailCommunication;
            ApexPages.Message successMessage = new ApexPages.Message(ApexPages.Severity.CONFIRM , 'Your email was sent to: ' + selectedCandidate.First_Name__c + ' ' + selectedCandidate.Last_Name__c);
            ApexPages.addMessage(successMessage);
        }catch(Exception e){
            ApexPages.Message failedMessage = new ApexPages.Message(ApexPages.Severity.ERROR , e.getMessage());
            ApexPages.addMessage(failedMessage);
        }
        return null;  
    }
    
     /*------------ Tests only below this line ------------*/
    static testMethod void testEmailSender(){
    EmailSender ttt = new EmailSender();
    ttt.getCandidates();
    ttt.sendEmail();
    
    }
    
}