src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Business Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product and Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Operations</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PositionsDynamicCall.cls
public class PositionsDynamicCall{
   
   public PositionsDynamicCall(){
   
   }
   
   public String receivedParameter{
       public get;
       public set;
   }

   public String getPositions(){
       String department = Apexpages.currentPage().getParameters().get('department');  
       String result = '';
       if(department != null){
            for (Position__c positionItem : [select Name from Position__c where Department__c =:department]){
                result += '<option value="' + positionItem.Name + '">' + positionItem.Name + '</option>';
            }
       }else{
           result += '<option value="">None</option>';
       }
       return result;
   }
   
   public void setPosition(String positions){
   
   }
}