src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Business Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product and Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Operations</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the position including its overview duties, responsibility and qualifications</description>
        <inlineHelpText>Description of the position including its overview duties, responsibility and qualifications</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Los Altos, CA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago, IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London, United Kingdom</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PositionParamController.cls
public class PositionParamController
{
    private String name;
    private Position__c p;
    
    public String getName() {
       name = System.currentPagereference().getParameters().get('positionName');
        return name;
    }
    
    public PositionParamController(ApexPages.StandardController stdController) {
    
      p = [SELECT Department__c,Location__c,Description__c FROM Position__c WHERE Name=:this.getName()].get(0);
    }
    
    public String getDescription() {
     return p.Description__c;
     }
     
     public String getLocation()  {
      
      return p.Location__c;
    }
    
     public String getDepartment()  {
      
      return p.Department__c;
    }
    
    public PageReference applyButtonClick() {
        return null;
    }

   
    public String getBoxDescription() {
        try {
            return [SELECT body FROM EmailTemplate WHERE Name =: 'Box Company Description'].body;
        } catch (System.QueryException e) {
            return 'Box';        
        }
    }
}